baseURL = 'https://jimmyvanlieu.com'
languageCode = 'en-us'
title = 'JVL'
theme = "shibui"


[params]
  author = "Jmi"
  email = "jimmyvanlieu@gmail.com"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true  # Enable HTML in markdown

[menu]
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 1
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
  [[menu.main]]
    name = "OPTCG"
    url = "/optcg/"
    weight = 3